name: Checkout
description: Manual Clean and Checkout
inputs:
  ref:
    type: string
    default: main
    required: false
    
runs:
  using: "composite"
  steps:
    - run: rm -rf ./build
    - run: git clean -ffdq || true
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: false
        lfs: true
        submodules: recursive
        fetch-depth: 0
        ref: ${{ inputs.ref }}
