# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    unlock_keychain(
      path: "login",
      password: ENV["KEYCHAIN_PASSWORD"]
    )
  end

  lane :deploy_testflight do

    xcodes(select_for_current_build_only: true)

    # increment_build_number({
    #   build_number: latest_testflight_build_number + 1
    # })

    build_app(
      workspace: "Unity-iPhone.xcworkspace", 
      scheme: "Unity-iPhone",
      export_options: {
        signingStyle: "automatic", 
        teamID: ENV["TEAM_ID"]
      }
    )

    # apple_id (env.PILOT_APPLE_ID): use app store connect > app > app information > apple id
    if ENV["SKIP_TESTFLIGHT"] == "true"
      UI.important("Skipped upload_to_testflight")
    else
      upload_to_testflight(
        skip_waiting_for_build_processing: true
      )
    end

  end

end
