name: Deploy testflight

on:
  workflow_call:
    inputs:
      app-identifier:
        type: string
        required: true
        description: "App Store Connect > App Information > Bundle ID"
      app-info-apple-id:
        type: string
        required: true
        description: "App Store Connect > App Information > Apple ID"
      slack-channel-id:
        type: string
        required: false
      skip-testflight:
        type: boolean
        required: false
        default: false

env:
  SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id || vars.SLACK_BUILD_CHANNEL_ID }}

jobs:
  deploy:
    runs-on:
      - self-hosted
      - macOS
    outputs:
      ts: ${{ steps.slack.outputs.ts }}
    steps:
      - uses: TinycellCorp/Actions/.github/actions/slack/status-message/started@main
        id: slack
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          title: "Deploy ${{ github.repository }} testflight"
          color: "#999"
          message: "Started"
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: TinycellCorp/Actions/.github/actions/cache@main
        with:
          platform: iOS
      - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          title: "Deploy ${{ github.repository }} testflight"
          color: "#ffa500"
          message: "Running unity"
          ts: ${{ steps.slack.outputs.ts }}
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          gitPrivateToken: ${{ github.token }}
          targetPlatform: iOS
          skipActivation: true
      - name: Checkout fastlane
        uses: actions/checkout@v4
        with:
          repository: TinycellCorp/Actions
          path: Actions
          sparse-checkout: |
            src/fastlane
      - name: Copy fastlane files
        run: cp -R Actions/src/fastlane/ build/iOS/iOS
      - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          title: "Deploy ${{ github.repository }} testflight"
          color: "#ffa500"
          message: "Running fastlane"
          ts: ${{ steps.slack.outputs.ts }}
      - name: Run deploy lane
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

          APP_IDENTIFIER: ${{ inputs.app-identifier }}
          PILOT_APPLE_ID: ${{ inputs.app-info-apple-id }}

          APPLE_ID: ${{ vars.APPLE_ID_SUPERLEE }}
          ITC_TEAM_ID: ${{ vars.ITC_TEAM_ID_SUPERLEE }}
          TEAM_ID: ${{ vars.TEAM_ID_SUPERLEE }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD_SUPERLEE }}

          SKIP_TESTFLIGHT: ${{ inputs.skip-testflight }}
        run: cd build/iOS/iOS && bundle exec fastlane ios deploy_testflight
  success:
    runs-on:
      - self-hosted
      - macOS
    needs: [deploy]
    if: success()
    steps:
      - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          title: "Deploy ${{ github.repository }} testflight"
          color: "#00ff00"
          message: "Deploy success"
          ts: ${{ needs.deploy.outputs.ts }}
  failure:
    runs-on:
      - self-hosted
      - macOS
    needs: [deploy]
    if: failure()
    steps:
      - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          title: "Deploy ${{ github.repository }} testflight"
          color: "#ff0000"
          message: "Deploy failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>"
          ts: ${{ needs.deploy.outputs.ts }}
