name: cURL Sample

on:
  workflow_dispatch:

jobs:
  run:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - run: which curl
      - shell: zsh {0}
        run: which curl
      - run: curl --version && curl --help
