name: cURL Sample

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
      
jobs:
  run:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - run: which curl
      - shell: zsh {0}
        run: which curl
      - run: curl --version && curl --help
      - uses: actions/checkout@v4
      - run: mkdir build && echo test >> build/test.txt
      - name: FileUpload to slack
        run: |
          curl -F file=@build/test.txt \
          -F "initial_comment=text" \
          -F channels=${{ inputs.channel }} \
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          https://slack.com/api/files.upload
