name: cURL Sample

on:
  workflow_dispatch:

jobs:
  run:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - run: which curl
      - shell: zsh {0}
        run: which curl
      - run: curl --version && curl --help
      - uses: actions/checkout@v4
      - run: mkdir build && echo test >> build/test.txt && cd build
      - name: FileUpload to slack
        run: |
          pwd &&
          curl -F "file=@test.txt" \
            -F "initial_comment=${{ inputs.platform }} build completed" \
            -F "channels=${{ inputs.channels }}" \
            -F "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
            https://slack.com/api/files.upload
