name: Deploy testflight
on:
  workflow_call:

jobs:
  build:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: TinycellCorp/Actions/.github/actions/cache@main
        with:
          platform: iOS
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          gitPrivateToken: ${{ github.token }}
          targetPlatform: iOS
          skipActivation: true
