name: External Build

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: Artifact
      repo:
        required: true
      ref:
        required: true
        default: main
      token:
        required: true
      platform:
        required: false
        default: Android
      channels:
        required: true
      
jobs:
  run:
    runs-on: 
      - self-hosted
      - macOS
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          token: ${{ inputs.token }}
          submodules: 'true'
      - uses: maxnowack/local-cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-${{ matrix.targetPlatform }}
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Artifact Upload to slack (Android)
        if: ${{ matrix.targetPlatform == 'Android' }}
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ inputs.token }}
          channel_id: ${{ inputs.channels }}
          file_path: 'build/Android/Android.apk'
          file_name: 'Android.apk'
          # file_name: '${{ inputs.name }} (${{ inputs.ref }}) - ${{ github.sha }}.apk'
          file_type: 'apk'
          initial_comment: '${{ inputs.repo }} (${{ inputs.ref }}) ${{ inputs.platform }} Build'
