name: Synology file station tests

on:
  workflow_dispatch:

jobs:
  create:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - id: auth
        uses: TinycellCorp/Actions/.github/actions/synology/auth@main
        with:
          host: ${{ vars.SYNOLOGY_HOST }}
          account: ${{ vars.SYNOLOGY_ACCOUNT }}
          passwd: ${{ secrets.SYNOLOGY_PASSWD }}
      - uses: TinycellCorp/Actions/.github/actions/synology/sharing/create@main
        with:
          host: ${{ vars.SYNOLOGY_HOST }}
          sid: ${{ steps.auth.outputs.sid }}
          path: /Tinycell/SlotsLive/Artifacts/SlotsLive-0.0.1544.zip
          expire: -v+10S
