name: Simulate slack messages

on:
  workflow_dispatch:
    inputs:
      channel-id:
        description: "Channel ID"
        required: true
      errors:
        type: boolean
        default: false
      force-failure:
        type: boolean
        default: false

jobs:
  send-messages:
    runs-on:
      - ubuntu-latest
    outputs:
      ts: ${{ steps.slack-started.outputs.ts }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack/status-message/started
        id: slack-started
        with:
          errors: ${{ inputs.errors }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#999"
          message: "Started"
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: ${{ inputs.errors }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#ffa500"
          message: "Updated"
          ts: ${{ steps.slack-started.outputs.ts }}
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: ${{ inputs.errors }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#00ff00"
          message: "Finished"
          ts: ${{ steps.slack-started.outputs.ts }}
      - if: ${{ inputs.force-failure }}
        run: exit 1
  failure:
    runs-on:
      - ubuntu-latest
    needs: [send-messages]
    if: failure()
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: ${{ inputs.errors }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#ff0000"
          message: "Failed <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>"
          ts: ${{ needs.send-messages.outputs.ts }}
