name: Simulate slack messages

on:
  workflow_dispatch:

env:
  CHANNEL_ID: C06SQLRK28Z # bot-test

jobs:
  send-messages:
    runs-on:
      - ubuntu-latest
      # - self-hosted
      # - macOS
    steps:
      - uses: actions/checkout@v4
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: auth.test
          token: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: ./.github/actions/slack/status-message/started
        id: slack-started
        with:
          errors: true
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.CHANNEL_ID }}
          title: "Simulating slack messages"
          color: "#FF0000"
          message: "Started"
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: true
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.CHANNEL_ID }}
          title: "Simulating slack messages"
          color: "#00FF00"
          message: "Updated"
          ts: ${{ steps.slack-started.outputs.ts }}
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: true
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.CHANNEL_ID }}
          title: "Simulating slack messages"
          color: "#0000FF"
          message: "Finished"
          ts: ${{ steps.slack-started.outputs.ts }}
