name: Simulate slack messages

on:
  workflow_dispatch:
    inputs:
      channel-id:
        description: "Channel ID"
        required: true

env:
  SLACK_ERRORS: false

jobs:
  send-messages:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack/status-message/started
        id: slack-started
        with:
          errors: ${{ env.SLACK_ERRORS }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#FF0000"
          message: "Started"
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: ${{ env.SLACK_ERRORS }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#00FF00"
          message: "Updated"
          ts: ${{ steps.slack-started.outputs.ts }}
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: ${{ env.SLACK_ERRORS }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#0000FF"
          message: "Finished"
          ts: ${{ steps.slack-started.outputs.ts }}
