name: Simulate slack messages

on:
  workflow_dispatch:
    inputs:
      channel-id:
        description: "Channel ID"
        required: true
      webhook-url:
        description: "Webhook URL"
        required: true

jobs:
  send-messages:
    runs-on:
      - ubuntu-latest
      # - self-hosted
      # - macOS
    steps:
      - uses: actions/checkout@v4
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: auth.test
          token: ${{ secrets.HASSAN_BOT_TOKEN }}
      - uses: ./.github/actions/slack/status-message/started
        id: slack-started
        with:
          errors: true
          bot-token: ${{ secrets.HASSAN_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#FF0000"
          message: "Started"
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: true
          bot-token: ${{ secrets.HASSAN_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#00FF00"
          message: "Updated"
          ts: ${{ steps.slack-started.outputs.ts }}
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: ./.github/actions/slack/status-message/updated
        with:
          errors: true
          bot-token: ${{ secrets.HASSAN_BOT_TOKEN }}
          channel-id: ${{ inputs.channel-id }}
          title: "Simulating slack messages"
          color: "#0000FF"
          message: "Finished"
          ts: ${{ steps.slack-started.outputs.ts }}
  webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: slackapi/slack-github-action@v2.0.0
        id: slack-started
        with:
          errors: true
          webhook: ${{ inputs.webhook-url }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Simulating slack messages*"
            attachments:
              - color: "#FF0000"
                fields:
                  - title: "Status"
                    short: true
                    value: "Started"
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "5" # for 60 seconds
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          webhook: ${{ inputs.webhook-url }}
          webhook-type: incoming-webhook
          payload: |
            ts: "${{ steps.slack-started.outputs.ts }}"
            text: "*Simulating slack messages*"
            attachments:
              - color: "#00FF00"
                fields:
                  - title: "Status"
                    short: true
                    value: "Updated"
