name: Build apk (slotslive)

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: false
        default: "SlotsLive"
      rclone-remote:
        type: string
        required: true

env:
  PLATFORM: Android
  ARTIFACT_EXTENSION: apk

jobs:
  build:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - name: Export slack title
        run: echo "MESSAGE_TITLE=*${{ github.repository }}* Deploy apk" >> "$GITHUB_ENV"

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Started

      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: TinycellCorp/Actions/.github/actions/cache@main
        with:
          platform: ${{ env.PLATFORM }}

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Unity

      - uses: siren403/unity-builder@custom
        id: unity
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          gitPrivateToken: ${{ github.token }}
          targetPlatform: ${{ env.PLATFORM }}
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.KEYSTORE_BASE64_TINYCELL_SLOTSLIVE }}
          androidKeystorePass: ${{ secrets.KEYSTORE_PASS_TINYCELL_SLOTSLIVE }}
          androidKeyaliasName: ${{ secrets.KEYSTORE_ALIAS_TINYCELL_SLOTSLIVE }}
          androidKeyaliasPass: ${{ secrets.KEYSTORE_ALIAS_PASS_TINYCELL_SLOTSLIVE }}
          skipActivation: true

      - name: Export artifact info
        run: |
          artifact_name="${{ inputs.app-name }}-${{ steps.unity.outputs.buildVersion }}"
          artifact_path="build/Android/$artifact_name.${{ env.ARTIFACT_EXTENSION }}"

          echo "ARTIFACT_NAME=$artifact_name" >> "$GITHUB_ENV"
          echo "ARTIFACT_PATH=$artifact_path" >> "$GITHUB_ENV"

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Uploading artifacts

      - name: Rename artifact
        run: mv build/Android/Android.apk "$ARTIFACT_PATH"
      - name: Artifacts to zip
        run: zip -r ${{ env.ARTIFACT_NAME }}.zip ./ServerData ${{ env.ARTIFACT_PATH }}
      - name: Artifacts upload to nas
        run: |
          artifacts_name=${{ env.ARTIFACT_NAME }}.zip
          artifacts_remote_path=${{ inputs.rclone-remote }}/${artifacts_name}
          
          rclone copyto ${artifacts_name} ${artifacts_remote_path} -P
          echo "ARTIFACTS_NAME=${artifacts_name}" >> "$GITHUB_ENV"

          artifacts_path=${artifacts_remote_path#*:}
          echo "ARTIFACTS_PATH=${artifacts_path}" >> "$GITHUB_ENV"
      - uses: TinycellCorp/Actions/.github/actions/synology/auth@main
        id: auth
        name: Synology auth
        with:
          host: ${{ vars.SYNOLOGY_HOST }}
          account: ${{ vars.SYNOLOGY_ACCOUNT }}
          passwd: ${{ secrets.SYNOLOGY_PASSWD }}
      - uses: TinycellCorp/Actions/.github/actions/synology/sharing/create@main
        id: share
        name: Create share link
        with:
          host: ${{ vars.SYNOLOGY_HOST }}
          sid: ${{ steps.auth.outputs.sid }}
          path: /${{ env.ARTIFACTS_PATH }}

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: success()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Success
            <${{ steps.share.outputs.url }}|${{ env.ARTIFACTS_NAME }}> (${{ steps.share.outputs.date_expired }})
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: failure()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Failure
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: cancelled()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.MESSAGE_TITLE }} :Cancelled
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
