name: Build apk (slotslive)

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: false
        default: "SlotsLive"
      # notify-channel-id:
      #   type: string
      #   required: false
      # upload-channel-id:
      #   type: string
      #   required: true
      # rlone-config-name:
      #   type: string
      #   required: true
      # skip-upload-asset-bundles:
      #   type: boolean
      #   required: false
      #   default: false

env:
  # SLACK_CHANNEL_ID: ${{ inputs.notify-channel-id || vars.SLACK_BUILD_CHANNEL_ID }}
  PLATFORM: Android
  ARTIFACT_EXTENSION: apk

jobs:
  build:
    runs-on:
      - self-hosted
      - macOS
    # outputs:
      # ts: ${{ steps.slack.outputs.ts }}
    steps:
      - name: Export slack title
        run: echo "SLACK_TITLE=*${{ github.repository }}* Deploy apk" >> "$GITHUB_ENV"

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Started

      # - uses: TinycellCorp/Actions/.github/actions/slack/status-message/started@main
      #   id: slack
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#999"
      #     message: "Started"

      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: TinycellCorp/Actions/.github/actions/cache@main
        with:
          platform: ${{ env.PLATFORM }}

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Running unity

      # - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#ffa500"
      #     message: "Running unity"
      #     ts: ${{ steps.slack.outputs.ts }}

      # Skip
      # - uses: siren403/unity-builder@custom
      #   id: unity
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     gitPrivateToken: ${{ github.token }}
      #     targetPlatform: ${{ env.PLATFORM }}
      #     androidKeystoreName: user.keystore
      #     androidKeystoreBase64: ${{ secrets.KEYSTORE_BASE64_TINYCELL_SLOTSLIVE }}
      #     androidKeystorePass: ${{ secrets.KEYSTORE_PASS_TINYCELL_SLOTSLIVE }}
      #     androidKeyaliasName: ${{ secrets.KEYSTORE_ALIAS_TINYCELL_SLOTSLIVE }}
      #     androidKeyaliasPass: ${{ secrets.KEYSTORE_ALIAS_PASS_TINYCELL_SLOTSLIVE }}
      #     skipActivation: true

      - name: Export artifact info
        run: |
          artifact_name="${{ inputs.app-name }}-${{ steps.unity.outputs.buildVersion }}"
          artifact_path="build/Android/$artifact_name.${{ env.ARTIFACT_EXTENSION }}"

          echo "ARTIFACT_NAME=$artifact_name" >> "$GITHUB_ENV"
          echo "ARTIFACT_PATH=$artifact_path" >> "$GITHUB_ENV"

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Uploading artifacts

      # TODO: Drive upload to add url
      # - uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#ffa500"
      #     message: "Uploading artifacts"
      #     ts: ${{ steps.slack.outputs.ts }}
      # - name: Rename artifact
      #   run: mv build/Android/Android.apk "$ARTIFACT_PATH"
      # - name: Artifacts to zip
      #   run: zip -r ${{ env.ARTIFACT_NAME }}.zip ./ServerData ${{ env.ARTIFACT_PATH }}
      # - name: Artifact upload to slack
      #   uses: MeilCli/slack-upload-file@v4
      #   with:
      #     slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel_id: ${{ inputs.upload-channel-id }}
      #     file_path: ${{ env.ARTIFACT_NAME }}.zip
      #     file_type: zip
      #     initial_comment: "${{ env.ARTIFACT_NAME }}"

      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: success()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Success
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: failure()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        if: cancelled()
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ env.SLACK_TITLE }}
            Cancelled - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
   
      # - name: Update success
      #   if: success()
      #   uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#00ff00"
      #     message: "Success"
      #     ts: ${{ steps.slack.outputs.ts }}
      # - name: Update failure
      #   if: failure()
      #   uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#ff0000"
      #     message: "Failure - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>"
      #     ts: ${{ steps.slack.outputs.ts }}
      # - name: Update cancelled
      #   if: cancelled()
      #   uses: TinycellCorp/Actions/.github/actions/slack/status-message/updated@main
      #   with:
      #     bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel-id: ${{ env.SLACK_CHANNEL_ID }}
      #     title: ${{ env.SLACK_TITLE }}
      #     color: "#ff0000"
      #     message: "Cancelled - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>"
      #     ts: ${{ steps.slack.outputs.ts }}
