name: Deploy testflight (SuperHit)

on:
  workflow_call:
    inputs:
      app-identifier:
        type: string
        required: true
        description: "App Store Connect > App Information > Bundle ID"
      app-info-apple-id:
        type: string
        required: true
        description: "App Store Connect > App Information > Apple ID"
      skip-testflight:
        type: boolean
        required: false
        default: false

jobs:
  deploy:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :Started
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: TinycellCorp/Actions/.github/actions/cache@main
        with:
          platform: iOS
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :Unity
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          gitPrivateToken: ${{ github.token }}
          targetPlatform: iOS
          skipActivation: true
          versioning: None
      - name: Checkout fastlane
        uses: actions/checkout@v4
        with:
          repository: TinycellCorp/Actions
          path: Actions
          sparse-checkout: |
            src/fastlane
      - name: Copy fastlane files
        run: cp -R Actions/src/fastlane/ build/iOS/iOS
      - uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :fastlane
      - name: Run deploy lane
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

          FL_XCODE_VERSION: ${{ vars.XCODE_VERSION_SUPERLEE }}

          APP_IDENTIFIER: ${{ inputs.app-identifier }}
          PILOT_APPLE_ID: ${{ inputs.app-info-apple-id }}

          APPLE_ID: ${{ vars.APPLE_ID_SUPERLEE }}
          ITC_TEAM_ID: ${{ vars.ITC_TEAM_ID_SUPERHIT }}
          TEAM_ID: ${{ vars.TEAM_ID_SUPERHIT }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD_SUPERLEE }}

          SKIP_TESTFLIGHT: ${{ inputs.skip-testflight }}
        run: cd build/iOS/iOS && bundle exec fastlane ios deploy_testflight
      - name: Update success
        if: success()
        uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :Success
      - name: Update failure
        if: failure()
        uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :Failure
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
      - name: Update cancelled
        if: cancelled()
        uses: TinycellCorp/Actions/.github/actions/synology-chat/text@main
        with:
          webhook-url: ${{ secrets.SYNOLOGY_CHAT_WEBHOOK_URL }}
          text: |
            ${{ github.repository }} Deploy testflight :Cancelled
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to runs>
